services:
  productscv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productservices_db_password
    ports:
      - "5433:5432"
    volumes:
      - productdb_vol:/var/lib/postgresql/data

volumes:
  productdb_vol: {}
